version: "3.9"

services:

  postgres:

    image: postgres:16

    environment:

      POSTGRES_DB: streaming_dw

      POSTGRES_USER: stream_admin

      POSTGRES_PASSWORD: stream_password

    ports:

      - "5432:5432"

  app:

    build: .

    depends_on:

      - postgres

    env_file:

      - .env
