services:

  postgres:

    image: postgres:17

    container_name: streaming_postgres

    restart: always

    environment:

      POSTGRES_USER: stream_admin

      POSTGRES_PASSWORD: stream_password

      POSTGRES_DB: streaming_dw

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data:
