services:

  postgres:

    image: postgres:17

    container_name: streaming_postgres

    restart: always

    environment:

      POSTGRES_USER: stream_admin

      POSTGRES_PASSWORD: stream_password

      POSTGRES_DB: streaming_dw

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:

    image: apache/airflow:2.10.0

    container_name: airflow_webserver

    restart: always

    ports:

      - "8080:8080"

    depends_on:

      - postgres

  airflow-scheduler:

    image: apache/airflow:2.10.0

    container_name: airflow_scheduler

    restart: always

    depends_on:

      - postgres

volumes:

  postgres_data:
